---
brew_packages:
  - ansible
  - asciinema
  - bat
  - eza
  - ffmpeg
  - git
  - git-extras
  - iperf
  - mas
  - starship
  - uv
  - wget
  - zsh

cask_packages:
  - ghostty
  - zed
  - miniconda
  - visual-studio-code
  - font-hack-nerd-font
  - slack
  - parsec
  - whatsapp
  - telegram
  - raycast
  - docker
  - google-chrome
  - vlc
  - autodesk-fusion
  - orcaslicer
  - prusaslicer
  - affinity-designer
  - affinity-photo
  - affinity-publisher
  - microsoft-excel
  - steam
