---
brew_packages:
  - ansible
  - asciinema
  - bat
  - eza
  - ffmpeg
  - iperf
  - mas
  - tmux
  - wget
  - zsh
  - starship

cask_packages:
  - docker
  - font-hack-nerd-font
  - google-chrome
  - visual-studio-code
  - vlc
  - autodesk-fusion
  - raycast
  - slack
  - orcaslicer
  - prusaslicer
  - parsec

mas_packages:
  - 1616822987 # Affinity Photo
  - 1616831348 # Affinity Designer
  - 1606941598 # Affinity Publisher
  - 462058435 # Microsof Excel
  - 310633997 # Whatsapp
  - 747648890 # Telegram
