---
brew_packages:
  - ansible
  - asciinema
  - bat
  - eza
  - ffmpeg
  - iperf
  - mas
  - tmux
  - wget
  - zsh
  - starship

cask_packages:
  - docker
  - font-hack-nerd-font
  - google-chrome
  - visual-studio-code
  - vlc
  - autodesk-fusion
  - raycast
  - slack
  - orcaslicer
  - prusaslicer
  - parsec
  - affinity-designer
  - affinity-photo
  - affinity-publisher
  - whatsapp
  - telegram
  - microsoft-excel
