---
brew_packages:
  - ansible
  - asciinema
  - bat
  - eza
  - ffmpeg
  - iperf
  - mas
  - tmux
  - wget
  - zsh

cask_packages:
  - docker
  - font-hack-nerd-font
  - google-chrome
  - telegram
  - visual-studio-code
  - vlc

mas_packages:
  - 1451685025 # Wireguard
  - 411643860 # DaisyDisk
  - 1295203466 # Microsoft Remote Desktop
  - 408981434 # iMovie
  - 430255202 # Mactracker
  - 409183694 # Keynote
  - 1289583905 # Pixelmator Pro
