###
### GPG
###

if [ -f "${HOME}/.gnupg/gpg-agent-info" ]; then
  . "${HOME}/.gnupg/gpg-agent-info"
  export SSH_AUTH_SOCK
  export GPG_TTY=$(tty)
  export GPG_AGENT_INFO
fi

###
### Exports (php-fpm, maven and $PATH)
###

# Yellow (temp) autosuggested string
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=3"

# Set dev.sh (https://github.com/frdmn/dev-sh) project path
export devsearch_projectspath="${HOME}/Development"

# $EDITOR
export EDITOR="nano"

# Update locale
export LANG="en_US.UTF-8"

# Add scripts directory to PATH
export PATH="${HOME}/.scripts:$PATH"

# uv
export PATH="/Users/roberto/.local/bin:$PATH"
