---
- name: "[﬒ dotfiles] Get list of files to symlink"
  ansible.builtin.shell: |
    ls -1 {{ ansible_env.PWD }}/files/dotfiles > /tmp/dotfilesToLink
  changed_when: false

- name: "[﬒ dotfiles] Store list of files into variable"
  ansible.builtin.command: "cat /tmp/dotfilesToLink"
  register: files_to_symlink
  changed_when: false
  tags:
    - skip_ansible_lint

- name: "[﬒ dotfiles] Set symlinks"
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/files/dotfiles/{{ item }}"
    path: "~/.{{ item }}"
    state: link
  with_items:
    - "{{ files_to_symlink.stdout_lines }}"
