---
- name: '[ macOS] Disable "Are you sure to open this application?" dialog'
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
    state: present

- name: "[ macOS] Check for software updates daily, not just once per week"
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: integer
    value: 1
    state: present

- name: "[ macOS] Disable smart quotes as they’re annoying when typing code"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: "[ macOS] Disable smart dashes as they’re annoying when typing code"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: "[ macOS] Increase speed of trackpad cursor movement"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.scaling
    type: float
    value: 3
    state: present

- name: "[ macOS] iterm2 - Specify the preferences directory"
  osx_defaults:
    domain: com.googlecode.iterm2.plist
    key: PrefsCustomFolder
    type: string
    value: /Users/jonas/.dotfiles/files/iterm2
    state: present

- name: "[ macOS] iterm2 - Use the custom preferences in the directory"
  osx_defaults:
    domain: com.googlecode.iterm2.plist
    key: LoadPrefsFromCustomFolder
    type: integer
    value: 1
    state: present

- name: "[ macOS] iterm2 - Save changes on exit 1/2"
  osx_defaults:
    domain: com.googlecode.iterm2.plist
    key: NoSyncNeverRemindPrefsChangesLostForFile
    type: integer
    value: 1
    state: present

- name: "[ macOS] iterm2 - Save changes on exit 2/2"
  osx_defaults:
    domain: com.googlecode.iterm2.plist
    key: NoSyncNeverRemindPrefsChangesLostForFile_selection
    type: integer
    value: 0
    state: present
