---
- name: "[ homebrew] Install Homebrew formulae"
  homebrew:
    name: "{{ item }}"
  loop: "{{ brew_packages }}"

- name: "[ homebrew] Install Homebrew casks"
  homebrew_cask:
    name: "{{ item }}"
  loop: "{{ cask_packages }}"
